#!/usr/bin/env python3
"""Turn a clean straight-line SVG (polygon/polyline only) into a hand-drawn looking sketch.

Output stays polyline-only (straight segments) so Unity can extract the strokes.

Usage: python sketchify_svg.py input.svg output.svg [--seed N] [--color #bbbbbb]
"""
import argparse
import math
import random
import re
import xml.etree.ElementTree as ET

SVG_NS = "http://www.w3.org/2000/svg"


def parse_points(s):
    nums = [float(v) for v in re.split(r"[\s,]+", s.strip()) if v]
    return [(nums[i], nums[i + 1]) for i in range(0, len(nums) - 1, 2)]


def smooth_noise(n, rng, octaves=3):
    """1D smooth noise in [-1,1] over n samples: sum of random-phase sines."""
    out = [0.0] * n
    for o in range(octaves):
        freq = (o + 1) * rng.uniform(0.8, 1.6)
        phase = rng.uniform(0, math.tau)
        amp = 1.0 / (o + 1)
        for i in range(n):
            t = i / max(n - 1, 1)
            out[i] += amp * math.sin(t * math.tau * freq + phase)
    m = max(abs(v) for v in out) or 1.0
    return [v / m for v in out]


def sketch_edge(p0, p1, rng, wobble, step, overshoot):
    """Return a list of points approximating a hand-drawn stroke from p0 to p1."""
    dx, dy = p1[0] - p0[0], p1[1] - p0[1]
    length = math.hypot(dx, dy)
    if length < 1e-6:
        return [p0]
    ux, uy = dx / length, dy / length      # along
    nx, ny = -uy, ux                       # perpendicular

    # pen starts/ends slightly short or past the corner, like a real stroke
    start = -rng.uniform(0, overshoot) if rng.random() < 0.5 else rng.uniform(0, overshoot * 0.4)
    end = length + (rng.uniform(0, overshoot) if rng.random() < 0.6 else -rng.uniform(0, overshoot * 0.4))

    n = max(2, int(math.ceil((end - start) / step)) + 1)
    noise = smooth_noise(n, rng)
    # taper wobble a bit at the ends so corners still land close to the target
    pts = []
    for i in range(n):
        t = start + (end - start) * i / (n - 1)
        u = i / (n - 1)
        taper = 0.4 + 0.6 * math.sin(u * math.pi)
        off = noise[i] * wobble * taper
        pts.append((p0[0] + ux * t + nx * off, p0[1] + uy * t + ny * off))
    return pts


def sketch_polyline(points, closed, rng, wobble, step, overshoot):
    """Each source edge becomes its own stroke (pen lifts at corners)."""
    strokes = []
    edges = list(zip(points, points[1:]))
    if closed and len(points) > 2:
        edges.append((points[-1], points[0]))
    for a, b in edges:
        # small random shift of the whole edge so overlapping passes don't coincide
        jx, jy = rng.uniform(-0.6, 0.6), rng.uniform(-0.6, 0.6)
        pts = sketch_edge((a[0] + jx, a[1] + jy), (b[0] + jx, b[1] + jy), rng, wobble, step, overshoot)
        strokes.append(pts)
    return strokes


def fmt(pts):
    return " ".join(f"{x:.2f},{y:.2f}" for x, y in pts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--color", default="#c8c8c8")
    ap.add_argument("--wobble", type=float, default=1.3, help="max perpendicular wobble in px")
    ap.add_argument("--step", type=float, default=4.0, help="segment length in px")
    ap.add_argument("--overshoot", type=float, default=4.0, help="max corner overshoot in px")
    ap.add_argument("--passes", type=int, default=2, help="sketch passes per edge")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    tree = ET.parse(args.input)
    root = tree.getroot()
    view_box = root.get("viewBox", "0 0 256 256")
    width = root.get("width", "256")
    height = root.get("height", "256")

    shapes = []
    for el in root.iter():
        tag = el.tag.split("}")[-1]
        if tag in ("polygon", "polyline"):
            shapes.append((tag == "polygon", parse_points(el.get("points", ""))))

    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="{SVG_NS}" viewBox="{view_box}" width="{width}" height="{height}" '
        f'fill="none" stroke="{args.color}" stroke-linecap="round" stroke-linejoin="round">',
        f'  <!-- generated by Tools/sketchify_svg.py from {args.input.replace(chr(92), "/")} seed={args.seed} -->',
    ]
    for si, (closed, pts) in enumerate(shapes):
        out.append(f'  <g id="shape{si}">')
        for p in range(args.passes):
            # first pass is the "committed" line, later passes are lighter search strokes
            sw = 1.6 if p == 0 else 1.0
            op = 1.0 if p == 0 else 0.55
            for ei, stroke in enumerate(sketch_polyline(pts, closed, rng, args.wobble, args.step, args.overshoot)):
                out.append(
                    f'    <polyline id="shape{si}_edge{ei}_pass{p}" stroke-width="{sw}" '
                    f'stroke-opacity="{op}" points="{fmt(stroke)}" />'
                )
        out.append("  </g>")
    out.append("</svg>")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {args.output}: {len(shapes)} shapes")


if __name__ == "__main__":
    main()
